### ISSUE TITLE
defining TREES and MODEL

### ISSUE THREAD

**Issue by RoelTim** [neerbek/taboo-core#1]
Hi, thank you for uploading your code.

I have a question about defining:
_export TREES=path-to-zip-file-with-data/trees0.zip\$test.txt
export MODEL=path-to-trained-model
export GLOVEPATH=path-to-glove_

I am not using my own data yet, but only the data that you uploaded online.

I runned _train_model.py_ without any issues and now I want to run _run_model.py_. I have _export GLOVEPATH=tests/resources/glove/_, but I do not know how to define _export TREES= _ and _export MODEL=_. I cannot find the updated model in my directory...

Could you give me a recommendation please?

**Comment by neerbek** [comment]
Hi RoelTim,
The default name for the saved model is save_best.txt (so that is the MODEL parameter) and the data is in 201/... (thats the TREES parameter). This should work
`OMP_NUM_THREADS=2 ipython3 functionality/run_model.py -- -inputtrees 201/dev_custom250_random.txt -inputmodel save_best.txt -nx 50 -nh 100 -batch_size 1000 -glove_path tests/resources/glove/
`
Note I am not actively updating this project anymore :)

**Comment by RoelTim** [comment]
Great, that worked, thank you!🥇
